// مولَّد من docs/data/vehicle-catalog.csv بالأمر npm run catalog:vehicles — لا تعدّله يدوياً.
import type { VehicleCatalogEntry } from "./vehicle-catalog-schema";

export const VEHICLE_ROWS: readonly VehicleCatalogEntry[] = [
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"كامري","modelEn":"Camry","aliases":["كامري","كامرى"],"generationCode":"XV40","yearFrom":2008,"yearTo":2011,"body":"sedan"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"كامري","modelEn":"Camry","aliases":["كامري","كامرى"],"generationCode":"XV50","yearFrom":2011,"yearTo":2017,"body":"sedan"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"كامري","modelEn":"Camry","aliases":["كامري","كامرى"],"generationCode":"XV70","yearFrom":2017,"yearTo":2024,"body":"sedan"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"كامري","modelEn":"Camry","aliases":["كامري","كامرى"],"generationCode":"XV80","yearFrom":2024,"yearTo":2027,"body":"sedan"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"كورولا","modelEn":"Corolla","aliases":["كرولا","كورلا"],"generationCode":"E150","yearFrom":2008,"yearTo":2013,"body":"sedan"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"كورولا","modelEn":"Corolla","aliases":["كرولا","كورلا"],"generationCode":"E170","yearFrom":2013,"yearTo":2019,"body":"sedan"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"كورولا","modelEn":"Corolla","aliases":["كرولا","كورلا"],"generationCode":"E210","yearFrom":2019,"yearTo":2027,"body":"sedan"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"يارس","modelEn":"Yaris","aliases":["ياريس"],"generationCode":"XP90","yearFrom":2008,"yearTo":2013,"body":"sedan"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"يارس","modelEn":"Yaris","aliases":["ياريس"],"generationCode":"XP150","yearFrom":2013,"yearTo":2022,"body":"sedan"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"يارس","modelEn":"Yaris","aliases":["ياريس"],"generationCode":"AC100","yearFrom":2022,"yearTo":2027,"body":"sedan"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"أفالون","modelEn":"Avalon","aliases":["افالون","افلون"],"generationCode":"XX30","yearFrom":2008,"yearTo":2012,"body":"sedan"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"أفالون","modelEn":"Avalon","aliases":["افالون","افلون"],"generationCode":"XX40","yearFrom":2012,"yearTo":2018,"body":"sedan"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"أفالون","modelEn":"Avalon","aliases":["افالون","افلون"],"generationCode":"XX50","yearFrom":2018,"yearTo":2022,"body":"sedan"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"كراون","modelEn":"Crown","aliases":["كراون تويوتا"],"generationCode":"S200","yearFrom":2008,"yearTo":2012,"body":"sedan"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"كراون","modelEn":"Crown","aliases":["كراون تويوتا"],"generationCode":"S210","yearFrom":2012,"yearTo":2018,"body":"sedan"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"كراون","modelEn":"Crown","aliases":["كراون تويوتا"],"generationCode":"S235","yearFrom":2023,"yearTo":2027,"body":"sedan"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"لاندكروزر","modelEn":"Land Cruiser","aliases":["لاند كروزر","جيب لاندكروزر","لاندكروزر ستيشن"],"generationCode":"J200","yearFrom":2008,"yearTo":2021,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"لاندكروزر","modelEn":"Land Cruiser","aliases":["لاند كروزر","جيب لاندكروزر","لاندكروزر ستيشن"],"generationCode":"J300","yearFrom":2021,"yearTo":2027,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"لاندكروزر 70","modelEn":"Land Cruiser 70","aliases":["شاص","ربع","لاندكروزر بيك اب","لاند كروزر بيك اب","لاندكروزر هاردتوب","شاص لاندكروزر","ربع لاندكروزر","لاندكروزر 79","لاندكروزر 76"],"generationCode":"J70","yearFrom":2008,"yearTo":2027,"body":"pickup"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"برادو","modelEn":"Land Cruiser Prado","aliases":["لاندكروزر برادو","لاند كروزر برادو"],"generationCode":"J120","yearFrom":2008,"yearTo":2009,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"برادو","modelEn":"Land Cruiser Prado","aliases":["لاندكروزر برادو","لاند كروزر برادو"],"generationCode":"J150","yearFrom":2009,"yearTo":2024,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"برادو","modelEn":"Land Cruiser Prado","aliases":["لاندكروزر برادو","لاند كروزر برادو"],"generationCode":"J250","yearFrom":2024,"yearTo":2027,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"إف جي كروزر","modelEn":"FJ Cruiser","aliases":["اف جي","اف جي كروزر","إف جي","FJ"],"generationCode":"XJ10","yearFrom":2008,"yearTo":2022,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"فورتشنر","modelEn":"Fortuner","aliases":["فورتشينر","فورجنر","فورتنر"],"generationCode":"AN50","yearFrom":2008,"yearTo":2015,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"فورتشنر","modelEn":"Fortuner","aliases":["فورتشينر","فورجنر","فورتنر"],"generationCode":"AN150","yearFrom":2015,"yearTo":2027,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"هايلكس","modelEn":"Hilux","aliases":["هايلوكس","هيلكس","هيلوكس"],"generationCode":"AN10","yearFrom":2008,"yearTo":2015,"body":"pickup"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"هايلكس","modelEn":"Hilux","aliases":["هايلوكس","هيلكس","هيلوكس"],"generationCode":"AN110","yearFrom":2015,"yearTo":2025,"body":"pickup"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"هايلكس","modelEn":"Hilux","aliases":["هايلوكس","هيلكس","هيلوكس"],"generationCode":"AN220","yearFrom":2025,"yearTo":2027,"body":"pickup"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"سيكويا","modelEn":"Sequoia","aliases":["سكويا"],"generationCode":"XK60","yearFrom":2008,"yearTo":2022,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"سيكويا","modelEn":"Sequoia","aliases":["سكويا"],"generationCode":"XK80","yearFrom":2022,"yearTo":2027,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"تندرا","modelEn":"Tundra","aliases":["توندرا"],"generationCode":"XK50","yearFrom":2008,"yearTo":2021,"body":"pickup"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"تندرا","modelEn":"Tundra","aliases":["توندرا"],"generationCode":"XK70","yearFrom":2021,"yearTo":2027,"body":"pickup"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"هايلاندر","modelEn":"Highlander","aliases":["هايلندر"],"generationCode":"XU40","yearFrom":2008,"yearTo":2013,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"هايلاندر","modelEn":"Highlander","aliases":["هايلندر"],"generationCode":"XU50","yearFrom":2013,"yearTo":2019,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"هايلاندر","modelEn":"Highlander","aliases":["هايلندر"],"generationCode":"XU70","yearFrom":2019,"yearTo":2026,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"هايلاندر","modelEn":"Highlander","aliases":["هايلندر"],"generationCode":"","yearFrom":2026,"yearTo":2027,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"راف فور","modelEn":"RAV4","aliases":["راف4","راف 4","راف"],"generationCode":"XA30","yearFrom":2008,"yearTo":2012,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"راف فور","modelEn":"RAV4","aliases":["راف4","راف 4","راف"],"generationCode":"XA40","yearFrom":2012,"yearTo":2018,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"راف فور","modelEn":"RAV4","aliases":["راف4","راف 4","راف"],"generationCode":"XA50","yearFrom":2018,"yearTo":2025,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"راف فور","modelEn":"RAV4","aliases":["راف4","راف 4","راف"],"generationCode":"XA60","yearFrom":2025,"yearTo":2027,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"سي إتش آر","modelEn":"C-HR","aliases":["سي اتش ار","CHR"],"generationCode":"AX10","yearFrom":2017,"yearTo":2023,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"رش","modelEn":"Rush","aliases":["راش"],"generationCode":"","yearFrom":2008,"yearTo":2017,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"رش","modelEn":"Rush","aliases":["راش"],"generationCode":"F800","yearFrom":2017,"yearTo":2027,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"رايز","modelEn":"Raize","aliases":["رايز تويوتا"],"generationCode":"A200","yearFrom":2022,"yearTo":2027,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"فيلوز","modelEn":"Veloz","aliases":["فيلوز تويوتا"],"generationCode":"","yearFrom":2022,"yearTo":2027,"body":"mpv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"أفانزا","modelEn":"Avanza","aliases":["افانزا","افنزا"],"generationCode":"F600","yearFrom":2008,"yearTo":2011,"body":"mpv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"أفانزا","modelEn":"Avanza","aliases":["افانزا","افنزا"],"generationCode":"F650","yearFrom":2011,"yearTo":2022,"body":"mpv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"أفانزا","modelEn":"Avanza","aliases":["افانزا","افنزا"],"generationCode":"","yearFrom":2022,"yearTo":2027,"body":"mpv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"إنوفا","modelEn":"Innova","aliases":["انوفا","اينوفا"],"generationCode":"AN40","yearFrom":2008,"yearTo":2016,"body":"mpv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"إنوفا","modelEn":"Innova","aliases":["انوفا","اينوفا"],"generationCode":"AN140","yearFrom":2016,"yearTo":2023,"body":"mpv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"إنوفا","modelEn":"Innova","aliases":["انوفا","اينوفا"],"generationCode":"AG10","yearFrom":2023,"yearTo":2027,"body":"mpv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"هايس","modelEn":"HiAce","aliases":["هاي اس","هايس فان","هايس باص"],"generationCode":"H200","yearFrom":2008,"yearTo":2019,"body":"van"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"هايس","modelEn":"HiAce","aliases":["هاي اس","هايس فان","هايس باص"],"generationCode":"H300","yearFrom":2019,"yearTo":2027,"body":"van"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"كوستر","modelEn":"Coaster","aliases":["باص كوستر"],"generationCode":"B50","yearFrom":2008,"yearTo":2017,"body":"van"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"كوستر","modelEn":"Coaster","aliases":["باص كوستر"],"generationCode":"B70","yearFrom":2017,"yearTo":2027,"body":"van"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"بريفيا","modelEn":"Previa","aliases":["بريفيا تويوتا"],"generationCode":"XR50","yearFrom":2008,"yearTo":2019,"body":"mpv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"جرانفيا","modelEn":"Granvia","aliases":["غرانفيا","قرانفيا"],"generationCode":"H300","yearFrom":2019,"yearTo":2027,"body":"mpv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"أوريون","modelEn":"Aurion","aliases":["اوريون","اورين"],"generationCode":"XV40","yearFrom":2008,"yearTo":2012,"body":"sedan"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"أوريون","modelEn":"Aurion","aliases":["اوريون","اورين"],"generationCode":"XV50","yearFrom":2012,"yearTo":2017,"body":"sedan"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"كورولا كروس","modelEn":"Corolla Cross","aliases":["كرولا كروس"],"generationCode":"XG10","yearFrom":2021,"yearTo":2027,"body":"suv"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"86","modelEn":"86","aliases":["جي تي 86","GT86","GR86","تويوتا 86","جي ار 86"],"generationCode":"ZN6","yearFrom":2012,"yearTo":2021,"body":"coupe"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"86","modelEn":"86","aliases":["جي تي 86","GT86","GR86","تويوتا 86","جي ار 86"],"generationCode":"ZN8","yearFrom":2021,"yearTo":2027,"body":"coupe"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"سوبرا","modelEn":"Supra","aliases":["سبرا","جي ار سوبرا"],"generationCode":"DB","yearFrom":2019,"yearTo":2027,"body":"coupe"},
  {"makeAr":"تويوتا","makeEn":"Toyota","modelAr":"bZ4X","modelEn":"bZ4X","aliases":["بي زد فور اكس","بي زد 4 اكس"],"generationCode":"EA10","yearFrom":2023,"yearTo":2027,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"باترول","modelEn":"Patrol","aliases":["بترول","نيسان باترول"],"generationCode":"Y61","yearFrom":2008,"yearTo":2010,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"باترول","modelEn":"Patrol","aliases":["بترول","نيسان باترول"],"generationCode":"Y62","yearFrom":2010,"yearTo":2024,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"باترول","modelEn":"Patrol","aliases":["بترول","نيسان باترول"],"generationCode":"Y63","yearFrom":2024,"yearTo":2027,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"باترول سفاري","modelEn":"Patrol Safari","aliases":["سفاري","باترول بيك اب","بيك اب باترول","سفاري بيك اب"],"generationCode":"Y61","yearFrom":2008,"yearTo":2024,"body":"pickup"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"صني","modelEn":"Sunny","aliases":["سني","صنى"],"generationCode":"N16","yearFrom":2008,"yearTo":2011,"body":"sedan"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"صني","modelEn":"Sunny","aliases":["سني","صنى"],"generationCode":"N17","yearFrom":2011,"yearTo":2020,"body":"sedan"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"صني","modelEn":"Sunny","aliases":["سني","صنى"],"generationCode":"N18","yearFrom":2020,"yearTo":2027,"body":"sedan"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"التيما","modelEn":"Altima","aliases":["ألتيما","التيمه"],"generationCode":"L32","yearFrom":2008,"yearTo":2012,"body":"sedan"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"التيما","modelEn":"Altima","aliases":["ألتيما","التيمه"],"generationCode":"L33","yearFrom":2012,"yearTo":2018,"body":"sedan"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"التيما","modelEn":"Altima","aliases":["ألتيما","التيمه"],"generationCode":"L34","yearFrom":2018,"yearTo":2027,"body":"sedan"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"ماكسيما","modelEn":"Maxima","aliases":["مكسيما"],"generationCode":"A34","yearFrom":2008,"yearTo":2008,"body":"sedan"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"ماكسيما","modelEn":"Maxima","aliases":["مكسيما"],"generationCode":"A35","yearFrom":2008,"yearTo":2015,"body":"sedan"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"ماكسيما","modelEn":"Maxima","aliases":["مكسيما"],"generationCode":"A36","yearFrom":2015,"yearTo":2023,"body":"sedan"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"سنترا","modelEn":"Sentra","aliases":["سينترا","سنتره"],"generationCode":"B16","yearFrom":2008,"yearTo":2012,"body":"sedan"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"سنترا","modelEn":"Sentra","aliases":["سينترا","سنتره"],"generationCode":"B17","yearFrom":2012,"yearTo":2019,"body":"sedan"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"سنترا","modelEn":"Sentra","aliases":["سينترا","سنتره"],"generationCode":"B18","yearFrom":2019,"yearTo":2025,"body":"sedan"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"سنترا","modelEn":"Sentra","aliases":["سينترا","سنتره"],"generationCode":"B19","yearFrom":2025,"yearTo":2027,"body":"sedan"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"تيدا","modelEn":"Tiida","aliases":["تيده","تييدا"],"generationCode":"C11","yearFrom":2008,"yearTo":2012,"body":"hatchback"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"تيدا","modelEn":"Tiida","aliases":["تيده","تييدا"],"generationCode":"C12","yearFrom":2012,"yearTo":2018,"body":"hatchback"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"ميكرا","modelEn":"Micra","aliases":["مكرا"],"generationCode":"K12","yearFrom":2008,"yearTo":2010,"body":"hatchback"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"ميكرا","modelEn":"Micra","aliases":["مكرا"],"generationCode":"K13","yearFrom":2010,"yearTo":2019,"body":"hatchback"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"باثفايندر","modelEn":"Pathfinder","aliases":["باثفندر","باث فايندر","باثفيندر"],"generationCode":"R51","yearFrom":2008,"yearTo":2012,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"باثفايندر","modelEn":"Pathfinder","aliases":["باثفندر","باث فايندر","باثفيندر"],"generationCode":"R52","yearFrom":2012,"yearTo":2021,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"باثفايندر","modelEn":"Pathfinder","aliases":["باثفندر","باث فايندر","باثفيندر"],"generationCode":"R53","yearFrom":2021,"yearTo":2027,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"إكس تريل","modelEn":"X-Trail","aliases":["اكس تريل","اكستريل","XTrail"],"generationCode":"T31","yearFrom":2008,"yearTo":2014,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"إكس تريل","modelEn":"X-Trail","aliases":["اكس تريل","اكستريل","XTrail"],"generationCode":"T32","yearFrom":2014,"yearTo":2022,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"إكس تريل","modelEn":"X-Trail","aliases":["اكس تريل","اكستريل","XTrail"],"generationCode":"T33","yearFrom":2022,"yearTo":2027,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"كيكس","modelEn":"Kicks","aliases":["ككس"],"generationCode":"P15","yearFrom":2017,"yearTo":2025,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"كيكس","modelEn":"Kicks","aliases":["ككس"],"generationCode":"P16","yearFrom":2025,"yearTo":2027,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"جوك","modelEn":"Juke","aliases":["جوكي"],"generationCode":"F15","yearFrom":2010,"yearTo":2019,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"نافارا","modelEn":"Navara","aliases":["نفارا","نافاره"],"generationCode":"D40","yearFrom":2008,"yearTo":2015,"body":"pickup"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"نافارا","modelEn":"Navara","aliases":["نفارا","نافاره"],"generationCode":"D23","yearFrom":2015,"yearTo":2025,"body":"pickup"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"نافارا","modelEn":"Navara","aliases":["نفارا","نافاره"],"generationCode":"D27","yearFrom":2025,"yearTo":2027,"body":"pickup"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"أورفان","modelEn":"Urvan","aliases":["اورفان","اورفن","يورفان"],"generationCode":"E25","yearFrom":2008,"yearTo":2012,"body":"van"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"أورفان","modelEn":"Urvan","aliases":["اورفان","اورفن","يورفان"],"generationCode":"E26","yearFrom":2012,"yearTo":2027,"body":"van"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"أرمادا","modelEn":"Armada","aliases":["ارمادا","ارماده"],"generationCode":"TA60","yearFrom":2008,"yearTo":2015,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"مورانو","modelEn":"Murano","aliases":["مورانو نيسان"],"generationCode":"Z51","yearFrom":2008,"yearTo":2014,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"مورانو","modelEn":"Murano","aliases":["مورانو نيسان"],"generationCode":"Z52","yearFrom":2014,"yearTo":2024,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"مورانو","modelEn":"Murano","aliases":["مورانو نيسان"],"generationCode":"Z53","yearFrom":2024,"yearTo":2027,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"قشقاي","modelEn":"Qashqai","aliases":["كشكاي","قاشقاي"],"generationCode":"J10","yearFrom":2008,"yearTo":2013,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"قشقاي","modelEn":"Qashqai","aliases":["كشكاي","قاشقاي"],"generationCode":"J11","yearFrom":2013,"yearTo":2021,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"قشقاي","modelEn":"Qashqai","aliases":["كشكاي","قاشقاي"],"generationCode":"J12","yearFrom":2021,"yearTo":2027,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"إكستيرا","modelEn":"Xterra","aliases":["اكستيرا","اكس تيرا","اكسترا"],"generationCode":"N50","yearFrom":2008,"yearTo":2015,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"إكستيرا","modelEn":"Xterra","aliases":["اكستيرا","اكس تيرا","اكسترا"],"generationCode":"","yearFrom":2020,"yearTo":2027,"body":"suv"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"370Z","modelEn":"370Z","aliases":["370 زد","نيسان 370"],"generationCode":"Z34","yearFrom":2008,"yearTo":2020,"body":"coupe"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"Z","modelEn":"Z","aliases":["زد","نيسان زد","فيرليدي"],"generationCode":"RZ34","yearFrom":2022,"yearTo":2027,"body":"coupe"},
  {"makeAr":"نيسان","makeEn":"Nissan","modelAr":"GT-R","modelEn":"GT-R","aliases":["جي تي ار","جي تي آر","GTR"],"generationCode":"R35","yearFrom":2008,"yearTo":2025,"body":"coupe"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"أكسنت","modelEn":"Accent","aliases":["اكسنت","اكسينت"],"generationCode":"MC","yearFrom":2008,"yearTo":2010,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"أكسنت","modelEn":"Accent","aliases":["اكسنت","اكسينت"],"generationCode":"RB","yearFrom":2010,"yearTo":2017,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"أكسنت","modelEn":"Accent","aliases":["اكسنت","اكسينت"],"generationCode":"HC","yearFrom":2017,"yearTo":2023,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"أكسنت","modelEn":"Accent","aliases":["اكسنت","اكسينت"],"generationCode":"BN7","yearFrom":2023,"yearTo":2027,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"إلنترا","modelEn":"Elantra","aliases":["النترا","الانترا","النتره","افانتي"],"generationCode":"HD","yearFrom":2008,"yearTo":2010,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"إلنترا","modelEn":"Elantra","aliases":["النترا","الانترا","النتره","افانتي"],"generationCode":"MD","yearFrom":2010,"yearTo":2015,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"إلنترا","modelEn":"Elantra","aliases":["النترا","الانترا","النتره","افانتي"],"generationCode":"AD","yearFrom":2015,"yearTo":2020,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"إلنترا","modelEn":"Elantra","aliases":["النترا","الانترا","النتره","افانتي"],"generationCode":"CN7","yearFrom":2020,"yearTo":2027,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"سوناتا","modelEn":"Sonata","aliases":["سوناته"],"generationCode":"NF","yearFrom":2008,"yearTo":2009,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"سوناتا","modelEn":"Sonata","aliases":["سوناته"],"generationCode":"YF","yearFrom":2009,"yearTo":2014,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"سوناتا","modelEn":"Sonata","aliases":["سوناته"],"generationCode":"LF","yearFrom":2014,"yearTo":2019,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"سوناتا","modelEn":"Sonata","aliases":["سوناته"],"generationCode":"DN8","yearFrom":2019,"yearTo":2027,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"أزيرا","modelEn":"Azera","aliases":["ازيرا","جراندير","جرانديور","غرانديور"],"generationCode":"TG","yearFrom":2008,"yearTo":2011,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"أزيرا","modelEn":"Azera","aliases":["ازيرا","جراندير","جرانديور","غرانديور"],"generationCode":"HG","yearFrom":2011,"yearTo":2016,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"أزيرا","modelEn":"Azera","aliases":["ازيرا","جراندير","جرانديور","غرانديور"],"generationCode":"IG","yearFrom":2016,"yearTo":2022,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"أزيرا","modelEn":"Azera","aliases":["ازيرا","جراندير","جرانديور","غرانديور"],"generationCode":"GN7","yearFrom":2022,"yearTo":2027,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"توسان","modelEn":"Tucson","aliases":["توكسون","تكسن","توسون"],"generationCode":"JM","yearFrom":2008,"yearTo":2009,"body":"suv"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"توسان","modelEn":"Tucson","aliases":["توكسون","تكسن","توسون"],"generationCode":"LM","yearFrom":2009,"yearTo":2015,"body":"suv"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"توسان","modelEn":"Tucson","aliases":["توكسون","تكسن","توسون"],"generationCode":"TL","yearFrom":2015,"yearTo":2020,"body":"suv"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"توسان","modelEn":"Tucson","aliases":["توكسون","تكسن","توسون"],"generationCode":"NX4","yearFrom":2020,"yearTo":2027,"body":"suv"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"سانتافي","modelEn":"Santa Fe","aliases":["سنتافي","سانتا في","سنتافيه"],"generationCode":"CM","yearFrom":2008,"yearTo":2012,"body":"suv"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"سانتافي","modelEn":"Santa Fe","aliases":["سنتافي","سانتا في","سنتافيه"],"generationCode":"DM","yearFrom":2012,"yearTo":2018,"body":"suv"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"سانتافي","modelEn":"Santa Fe","aliases":["سنتافي","سانتا في","سنتافيه"],"generationCode":"TM","yearFrom":2018,"yearTo":2023,"body":"suv"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"سانتافي","modelEn":"Santa Fe","aliases":["سنتافي","سانتا في","سنتافيه"],"generationCode":"MX5","yearFrom":2023,"yearTo":2027,"body":"suv"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"كريتا","modelEn":"Creta","aliases":["كريتا هيونداي"],"generationCode":"GS","yearFrom":2016,"yearTo":2020,"body":"suv"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"كريتا","modelEn":"Creta","aliases":["كريتا هيونداي"],"generationCode":"SU2","yearFrom":2020,"yearTo":2027,"body":"suv"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"كونا","modelEn":"Kona","aliases":["كونا هيونداي"],"generationCode":"OS","yearFrom":2017,"yearTo":2023,"body":"suv"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"كونا","modelEn":"Kona","aliases":["كونا هيونداي"],"generationCode":"SX2","yearFrom":2023,"yearTo":2027,"body":"suv"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"باليسيد","modelEn":"Palisade","aliases":["باليسد","باليسايد"],"generationCode":"LX2","yearFrom":2019,"yearTo":2025,"body":"suv"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"باليسيد","modelEn":"Palisade","aliases":["باليسد","باليسايد"],"generationCode":"LX3","yearFrom":2025,"yearTo":2027,"body":"suv"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"ستاريا","modelEn":"Staria","aliases":["ستاريا هيونداي"],"generationCode":"US4","yearFrom":2021,"yearTo":2027,"body":"van"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"H-1","modelEn":"H-1","aliases":["اتش ون","إتش ون","H1","ستاريكس"],"generationCode":"TQ","yearFrom":2008,"yearTo":2021,"body":"van"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"فينيو","modelEn":"Venue","aliases":["فنيو"],"generationCode":"QX","yearFrom":2019,"yearTo":2025,"body":"suv"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"فينيو","modelEn":"Venue","aliases":["فنيو"],"generationCode":"QU2","yearFrom":2025,"yearTo":2027,"body":"suv"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"فيلوستر","modelEn":"Veloster","aliases":["فلوستر"],"generationCode":"FS","yearFrom":2011,"yearTo":2018,"body":"hatchback"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"فيلوستر","modelEn":"Veloster","aliases":["فلوستر"],"generationCode":"JS","yearFrom":2018,"yearTo":2022,"body":"hatchback"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"جينيسيس","modelEn":"Genesis","aliases":["جنسس","جنيسس","جينيسس","جينسس"],"generationCode":"BH","yearFrom":2008,"yearTo":2013,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"جينيسيس","modelEn":"Genesis","aliases":["جنسس","جنيسس","جينيسس","جينسس"],"generationCode":"DH","yearFrom":2013,"yearTo":2016,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"جينيسيس كوبيه","modelEn":"Genesis Coupe","aliases":["جنسس كوبيه","جينيسيس كوبي"],"generationCode":"BK","yearFrom":2009,"yearTo":2016,"body":"coupe"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"سنتنيال","modelEn":"Centennial","aliases":["سنتينيال","إكوس","ايكوس"],"generationCode":"LZ","yearFrom":2008,"yearTo":2009,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"سنتنيال","modelEn":"Centennial","aliases":["سنتينيال","إكوس","ايكوس"],"generationCode":"VI","yearFrom":2009,"yearTo":2016,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"فيراكروز","modelEn":"Veracruz","aliases":["فيراكروس"],"generationCode":"EN","yearFrom":2008,"yearTo":2012,"body":"suv"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"أيونيك","modelEn":"Ioniq","aliases":["ايونيك"],"generationCode":"AE","yearFrom":2017,"yearTo":2022,"body":"hatchback"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"أيونيك 5","modelEn":"Ioniq 5","aliases":["ايونيك 5"],"generationCode":"NE","yearFrom":2022,"yearTo":2027,"body":"suv"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"أيونيك 6","modelEn":"Ioniq 6","aliases":["ايونيك 6"],"generationCode":"CE","yearFrom":2023,"yearTo":2027,"body":"sedan"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"ستارجيزر","modelEn":"Stargazer","aliases":["ستار جيزر","ستارقيزر"],"generationCode":"KS","yearFrom":2022,"yearTo":2027,"body":"mpv"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"i10","modelEn":"i10","aliases":["اي تن","اي 10","جراند اي 10","Grand i10"],"generationCode":"PA","yearFrom":2008,"yearTo":2013,"body":"hatchback"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"i10","modelEn":"i10","aliases":["اي تن","اي 10","جراند اي 10","Grand i10"],"generationCode":"BA","yearFrom":2013,"yearTo":2020,"body":"hatchback"},
  {"makeAr":"هيونداي","makeEn":"Hyundai","modelAr":"i10","modelEn":"i10","aliases":["اي تن","اي 10","جراند اي 10","Grand i10"],"generationCode":"","yearFrom":2020,"yearTo":2027,"body":"hatchback"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"أكورد","modelEn":"Accord","aliases":["اكورد","اكرد"],"generationCode":"CP","yearFrom":2008,"yearTo":2012,"body":"sedan"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"أكورد","modelEn":"Accord","aliases":["اكورد","اكرد"],"generationCode":"CR","yearFrom":2012,"yearTo":2017,"body":"sedan"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"أكورد","modelEn":"Accord","aliases":["اكورد","اكرد"],"generationCode":"CV","yearFrom":2017,"yearTo":2023,"body":"sedan"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"أكورد","modelEn":"Accord","aliases":["اكورد","اكرد"],"generationCode":"CY","yearFrom":2023,"yearTo":2027,"body":"sedan"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"سيفيك","modelEn":"Civic","aliases":["سيفك","سفك"],"generationCode":"FD","yearFrom":2008,"yearTo":2011,"body":"sedan"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"سيفيك","modelEn":"Civic","aliases":["سيفك","سفك"],"generationCode":"FB","yearFrom":2011,"yearTo":2015,"body":"sedan"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"سيفيك","modelEn":"Civic","aliases":["سيفك","سفك"],"generationCode":"FC","yearFrom":2015,"yearTo":2021,"body":"sedan"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"سيفيك","modelEn":"Civic","aliases":["سيفك","سفك"],"generationCode":"FE","yearFrom":2021,"yearTo":2027,"body":"sedan"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"سيتي","modelEn":"City","aliases":["ستي","هوندا سيتي"],"generationCode":"GM2","yearFrom":2008,"yearTo":2013,"body":"sedan"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"سيتي","modelEn":"City","aliases":["ستي","هوندا سيتي"],"generationCode":"GM6","yearFrom":2013,"yearTo":2020,"body":"sedan"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"سيتي","modelEn":"City","aliases":["ستي","هوندا سيتي"],"generationCode":"GN","yearFrom":2020,"yearTo":2027,"body":"sedan"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"سي آر في","modelEn":"CR-V","aliases":["سي ار في","CRV"],"generationCode":"RE","yearFrom":2008,"yearTo":2012,"body":"suv"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"سي آر في","modelEn":"CR-V","aliases":["سي ار في","CRV"],"generationCode":"RM","yearFrom":2012,"yearTo":2017,"body":"suv"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"سي آر في","modelEn":"CR-V","aliases":["سي ار في","CRV"],"generationCode":"RW","yearFrom":2017,"yearTo":2023,"body":"suv"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"سي آر في","modelEn":"CR-V","aliases":["سي ار في","CRV"],"generationCode":"RS","yearFrom":2023,"yearTo":2027,"body":"suv"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"إتش آر في","modelEn":"HR-V","aliases":["اتش ار في","HRV"],"generationCode":"RU","yearFrom":2015,"yearTo":2022,"body":"suv"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"إتش آر في","modelEn":"HR-V","aliases":["اتش ار في","HRV"],"generationCode":"RV","yearFrom":2022,"yearTo":2027,"body":"suv"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"زد آر في","modelEn":"ZR-V","aliases":["زد ار في","ZRV"],"generationCode":"RZ","yearFrom":2023,"yearTo":2027,"body":"suv"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"بايلوت","modelEn":"Pilot","aliases":["بيلوت","بايلت"],"generationCode":"YF1/2","yearFrom":2008,"yearTo":2008,"body":"suv"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"بايلوت","modelEn":"Pilot","aliases":["بيلوت","بايلت"],"generationCode":"YF3/4","yearFrom":2008,"yearTo":2015,"body":"suv"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"بايلوت","modelEn":"Pilot","aliases":["بيلوت","بايلت"],"generationCode":"YF5/6","yearFrom":2015,"yearTo":2022,"body":"suv"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"بايلوت","modelEn":"Pilot","aliases":["بيلوت","بايلت"],"generationCode":"YG1/2","yearFrom":2022,"yearTo":2027,"body":"suv"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"أوديسي","modelEn":"Odyssey","aliases":["اوديسي","اوديسا"],"generationCode":"RL3/4","yearFrom":2008,"yearTo":2010,"body":"mpv"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"أوديسي","modelEn":"Odyssey","aliases":["اوديسي","اوديسا"],"generationCode":"RL5","yearFrom":2010,"yearTo":2017,"body":"mpv"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"أوديسي","modelEn":"Odyssey","aliases":["اوديسي","اوديسا"],"generationCode":"RL6","yearFrom":2017,"yearTo":2027,"body":"mpv"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"أوديسي J","modelEn":"Odyssey J","aliases":["اوديسي جي","اوديسي الياباني"],"generationCode":"RB3/4","yearFrom":2008,"yearTo":2013,"body":"mpv"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"أوديسي J","modelEn":"Odyssey J","aliases":["اوديسي جي","اوديسي الياباني"],"generationCode":"RC","yearFrom":2013,"yearTo":2027,"body":"mpv"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"جاز","modelEn":"Jazz","aliases":["فيت","هوندا فيت","جاز هوندا"],"generationCode":"GE","yearFrom":2008,"yearTo":2013,"body":"hatchback"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"جاز","modelEn":"Jazz","aliases":["فيت","هوندا فيت","جاز هوندا"],"generationCode":"GK","yearFrom":2013,"yearTo":2020,"body":"hatchback"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"جاز","modelEn":"Jazz","aliases":["فيت","هوندا فيت","جاز هوندا"],"generationCode":"GR","yearFrom":2020,"yearTo":2027,"body":"hatchback"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"ليجند","modelEn":"Legend","aliases":["ليجيند","لجند"],"generationCode":"KB","yearFrom":2008,"yearTo":2012,"body":"sedan"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"ليجند","modelEn":"Legend","aliases":["ليجيند","لجند"],"generationCode":"KC","yearFrom":2014,"yearTo":2021,"body":"sedan"},
  {"makeAr":"هوندا","makeEn":"Honda","modelAr":"كروس تور","modelEn":"Crosstour","aliases":["كروستور","اكورد كروس تور"],"generationCode":"TF","yearFrom":2010,"yearTo":2015,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"إكسبلورر","modelEn":"Explorer","aliases":["اكسبلورر","اكسبلور","اكسبلوره"],"generationCode":"U251","yearFrom":2008,"yearTo":2010,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"إكسبلورر","modelEn":"Explorer","aliases":["اكسبلورر","اكسبلور","اكسبلوره"],"generationCode":"U502","yearFrom":2010,"yearTo":2019,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"إكسبلورر","modelEn":"Explorer","aliases":["اكسبلورر","اكسبلور","اكسبلوره"],"generationCode":"U625","yearFrom":2019,"yearTo":2027,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"إكسبيديشن","modelEn":"Expedition","aliases":["اكسبيديشن","اكسبديشن","اكسبدشن"],"generationCode":"U324","yearFrom":2008,"yearTo":2017,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"إكسبيديشن","modelEn":"Expedition","aliases":["اكسبيديشن","اكسبديشن","اكسبدشن"],"generationCode":"U553","yearFrom":2017,"yearTo":2025,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"إكسبيديشن","modelEn":"Expedition","aliases":["اكسبيديشن","اكسبديشن","اكسبدشن"],"generationCode":"U717","yearFrom":2025,"yearTo":2027,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"F-150","modelEn":"F-150","aliases":["اف 150","اف150","F150","فورد 150","ف 150"],"generationCode":"P221","yearFrom":2008,"yearTo":2008,"body":"pickup"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"F-150","modelEn":"F-150","aliases":["اف 150","اف150","F150","فورد 150","ف 150"],"generationCode":"P415","yearFrom":2008,"yearTo":2014,"body":"pickup"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"F-150","modelEn":"F-150","aliases":["اف 150","اف150","F150","فورد 150","ف 150"],"generationCode":"P552","yearFrom":2014,"yearTo":2020,"body":"pickup"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"F-150","modelEn":"F-150","aliases":["اف 150","اف150","F150","فورد 150","ف 150"],"generationCode":"P702","yearFrom":2020,"yearTo":2027,"body":"pickup"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"سوبر ديوتي","modelEn":"Super Duty","aliases":["سوبر ديوتى","F-250","F-350","اف 250","اف 350"],"generationCode":"P356","yearFrom":2008,"yearTo":2010,"body":"pickup"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"سوبر ديوتي","modelEn":"Super Duty","aliases":["سوبر ديوتى","F-250","F-350","اف 250","اف 350"],"generationCode":"P473","yearFrom":2010,"yearTo":2016,"body":"pickup"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"سوبر ديوتي","modelEn":"Super Duty","aliases":["سوبر ديوتى","F-250","F-350","اف 250","اف 350"],"generationCode":"P558","yearFrom":2016,"yearTo":2022,"body":"pickup"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"سوبر ديوتي","modelEn":"Super Duty","aliases":["سوبر ديوتى","F-250","F-350","اف 250","اف 350"],"generationCode":"P708","yearFrom":2022,"yearTo":2027,"body":"pickup"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"تورس","modelEn":"Taurus","aliases":["توروس","تاورس"],"generationCode":"","yearFrom":2010,"yearTo":2020,"body":"sedan"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"تورس","modelEn":"Taurus","aliases":["توروس","تاورس"],"generationCode":"","yearFrom":2020,"yearTo":2023,"body":"sedan"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"تورس","modelEn":"Taurus","aliases":["توروس","تاورس"],"generationCode":"","yearFrom":2023,"yearTo":2027,"body":"sedan"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"فيوجن","modelEn":"Fusion","aliases":["فيوشن","فيوجين"],"generationCode":"","yearFrom":2008,"yearTo":2012,"body":"sedan"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"فيوجن","modelEn":"Fusion","aliases":["فيوشن","فيوجين"],"generationCode":"","yearFrom":2012,"yearTo":2020,"body":"sedan"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"موستنج","modelEn":"Mustang","aliases":["موستنق","ماستنج","موستانج","موستنغ"],"generationCode":"S197","yearFrom":2008,"yearTo":2014,"body":"coupe"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"موستنج","modelEn":"Mustang","aliases":["موستنق","ماستنج","موستانج","موستنغ"],"generationCode":"S550","yearFrom":2014,"yearTo":2023,"body":"coupe"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"موستنج","modelEn":"Mustang","aliases":["موستنق","ماستنج","موستانج","موستنغ"],"generationCode":"S650","yearFrom":2023,"yearTo":2027,"body":"coupe"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"إيدج","modelEn":"Edge","aliases":["ايدج","ادج"],"generationCode":"U387","yearFrom":2008,"yearTo":2014,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"إيدج","modelEn":"Edge","aliases":["ايدج","ادج"],"generationCode":"CD539","yearFrom":2014,"yearTo":2023,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"إيدج","modelEn":"Edge","aliases":["ايدج","ادج"],"generationCode":"CDX706","yearFrom":2023,"yearTo":2027,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"إسكيب","modelEn":"Escape","aliases":["اسكيب","اسكايب"],"generationCode":"","yearFrom":2008,"yearTo":2012,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"إسكيب","modelEn":"Escape","aliases":["اسكيب","اسكايب"],"generationCode":"","yearFrom":2012,"yearTo":2019,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"إسكيب","modelEn":"Escape","aliases":["اسكيب","اسكايب"],"generationCode":"","yearFrom":2019,"yearTo":2027,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"رينجر","modelEn":"Ranger","aliases":["رنجر","رينجر فورد"],"generationCode":"","yearFrom":2008,"yearTo":2011,"body":"pickup"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"رينجر","modelEn":"Ranger","aliases":["رنجر","رينجر فورد"],"generationCode":"P375","yearFrom":2011,"yearTo":2022,"body":"pickup"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"رينجر","modelEn":"Ranger","aliases":["رنجر","رينجر فورد"],"generationCode":"P703","yearFrom":2022,"yearTo":2027,"body":"pickup"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"تيريتوري","modelEn":"Territory","aliases":["تريتوري","تيريتوري فورد"],"generationCode":"CX743MCA","yearFrom":2023,"yearTo":2027,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"فوكس","modelEn":"Focus","aliases":["فوكاس","فوكس فورد"],"generationCode":"C307","yearFrom":2008,"yearTo":2011,"body":"sedan"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"فوكس","modelEn":"Focus","aliases":["فوكاس","فوكس فورد"],"generationCode":"C346","yearFrom":2011,"yearTo":2018,"body":"sedan"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"فوكس","modelEn":"Focus","aliases":["فوكاس","فوكس فورد"],"generationCode":"C519","yearFrom":2018,"yearTo":2022,"body":"sedan"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"فيجو","modelEn":"Figo","aliases":["فيغو"],"generationCode":"B517","yearFrom":2010,"yearTo":2015,"body":"hatchback"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"فيجو","modelEn":"Figo","aliases":["فيغو"],"generationCode":"B562","yearFrom":2015,"yearTo":2021,"body":"hatchback"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"فليكس","modelEn":"Flex","aliases":["فلكس"],"generationCode":"","yearFrom":2008,"yearTo":2019,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"كراون فكتوريا","modelEn":"Crown Victoria","aliases":["كراون فيكتوريا","فكتوريا","فيكتوريا"],"generationCode":"EN114","yearFrom":2008,"yearTo":2012,"body":"sedan"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"إيكوسبورت","modelEn":"EcoSport","aliases":["ايكوسبورت","ايكو سبورت","اكوسبورت"],"generationCode":"B515","yearFrom":2013,"yearTo":2022,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"برونكو","modelEn":"Bronco","aliases":["برانكو","برونكو فورد"],"generationCode":"U725","yearFrom":2021,"yearTo":2027,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"إيفرست","modelEn":"Everest","aliases":["ايفرست","افرست"],"generationCode":"U375","yearFrom":2015,"yearTo":2022,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"إيفرست","modelEn":"Everest","aliases":["ايفرست","افرست"],"generationCode":"U704","yearFrom":2022,"yearTo":2027,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"موستنج ماك-إي","modelEn":"Mustang Mach-E","aliases":["ماك اي","ماك-إي","موستنج ماك اي","ماخ اي"],"generationCode":"CX727","yearFrom":2021,"yearTo":2027,"body":"suv"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"ترانزيت","modelEn":"Transit","aliases":["ترانزت","فان ترانزيت"],"generationCode":"","yearFrom":2008,"yearTo":2014,"body":"van"},
  {"makeAr":"فورد","makeEn":"Ford","modelAr":"ترانزيت","modelEn":"Transit","aliases":["ترانزت","فان ترانزيت"],"generationCode":"","yearFrom":2014,"yearTo":2027,"body":"van"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"يوكن","modelEn":"Yukon","aliases":["يوكون","جمس يوكن"],"generationCode":"GMT900","yearFrom":2008,"yearTo":2014,"body":"suv"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"يوكن","modelEn":"Yukon","aliases":["يوكون","جمس يوكن"],"generationCode":"K2XX","yearFrom":2014,"yearTo":2020,"body":"suv"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"يوكن","modelEn":"Yukon","aliases":["يوكون","جمس يوكن"],"generationCode":"T1XX","yearFrom":2020,"yearTo":2027,"body":"suv"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"يوكن XL","modelEn":"Yukon XL","aliases":["يوكن اكس ال","يوكون اكس ال","يوكن اكسل"],"generationCode":"GMT900","yearFrom":2008,"yearTo":2014,"body":"suv"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"يوكن XL","modelEn":"Yukon XL","aliases":["يوكن اكس ال","يوكون اكس ال","يوكن اكسل"],"generationCode":"K2XX","yearFrom":2014,"yearTo":2020,"body":"suv"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"يوكن XL","modelEn":"Yukon XL","aliases":["يوكن اكس ال","يوكون اكس ال","يوكن اكسل"],"generationCode":"T1XX","yearFrom":2020,"yearTo":2027,"body":"suv"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"سييرا","modelEn":"Sierra","aliases":["سيرا","سييرا 1500","جمس سييرا"],"generationCode":"GMT900","yearFrom":2008,"yearTo":2013,"body":"pickup"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"سييرا","modelEn":"Sierra","aliases":["سيرا","سييرا 1500","جمس سييرا"],"generationCode":"K2XX","yearFrom":2013,"yearTo":2018,"body":"pickup"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"سييرا","modelEn":"Sierra","aliases":["سيرا","سييرا 1500","جمس سييرا"],"generationCode":"T1XX","yearFrom":2018,"yearTo":2027,"body":"pickup"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"سييرا HD","modelEn":"Sierra HD","aliases":["سييرا اتش دي","سيرا اتش دي","سييرا 2500","سييرا 3500"],"generationCode":"GMT900","yearFrom":2008,"yearTo":2014,"body":"pickup"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"سييرا HD","modelEn":"Sierra HD","aliases":["سييرا اتش دي","سيرا اتش دي","سييرا 2500","سييرا 3500"],"generationCode":"K2XX","yearFrom":2014,"yearTo":2019,"body":"pickup"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"سييرا HD","modelEn":"Sierra HD","aliases":["سييرا اتش دي","سيرا اتش دي","سييرا 2500","سييرا 3500"],"generationCode":"T1XX","yearFrom":2019,"yearTo":2027,"body":"pickup"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"أكاديا","modelEn":"Acadia","aliases":["اكاديا","اكاديه"],"generationCode":"GMT968","yearFrom":2008,"yearTo":2016,"body":"suv"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"أكاديا","modelEn":"Acadia","aliases":["اكاديا","اكاديه"],"generationCode":"C1XX","yearFrom":2016,"yearTo":2024,"body":"suv"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"أكاديا","modelEn":"Acadia","aliases":["اكاديا","اكاديه"],"generationCode":"","yearFrom":2024,"yearTo":2027,"body":"suv"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"تيرين","modelEn":"Terrain","aliases":["تيرن","تيرين جمس"],"generationCode":"GMT177","yearFrom":2010,"yearTo":2017,"body":"suv"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"تيرين","modelEn":"Terrain","aliases":["تيرن","تيرين جمس"],"generationCode":"D2XX","yearFrom":2017,"yearTo":2024,"body":"suv"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"تيرين","modelEn":"Terrain","aliases":["تيرن","تيرين جمس"],"generationCode":"","yearFrom":2024,"yearTo":2027,"body":"suv"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"سافانا","modelEn":"Savana","aliases":["سفانا","سافانا جمس"],"generationCode":"GMT610","yearFrom":2008,"yearTo":2027,"body":"van"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"إنفوي","modelEn":"Envoy","aliases":["انفوي","انفوى"],"generationCode":"GMT360","yearFrom":2008,"yearTo":2009,"body":"suv"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"كانيون","modelEn":"Canyon","aliases":["كنيون"],"generationCode":"GMT355","yearFrom":2008,"yearTo":2012,"body":"pickup"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"كانيون","modelEn":"Canyon","aliases":["كنيون"],"generationCode":"31XX","yearFrom":2015,"yearTo":2022,"body":"pickup"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"كانيون","modelEn":"Canyon","aliases":["كنيون"],"generationCode":"31XX-2","yearFrom":2023,"yearTo":2027,"body":"pickup"},
  {"makeAr":"جمس","makeEn":"GMC","modelAr":"هامر EV","modelEn":"Hummer EV","aliases":["همر","هامر","هامر اي في","همر اي في"],"generationCode":"BT1","yearFrom":2022,"yearTo":2027,"body":"pickup"},
];
